In [189]:
import pandas as pd
import numpy as np

In [190]:
from sklearn.datasets import load_diabetes
diabetes=load_diabetes()
X=diabetes.data
y=diabetes.target

In [191]:
df=pd.DataFrame(X,columns=diabetes.feature_names)
df['target']=y

In [192]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,442.000000
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17,152.133484
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,77.093005
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01,25.000000
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02,87.000000
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03,140.500000
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02,211.500000
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01,346.000000

In [193]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [194]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train

array([[ 0.07076875,  0.05068012,  0.01211685, ...,  0.03430886,
         0.02736405, -0.0010777 ],
       [-0.00914709,  0.05068012, -0.01806189, ...,  0.07120998,
         0.00027248,  0.01963284],
       [ 0.00538306, -0.04464164,  0.04984027, ..., -0.00259226,
         0.01703607, -0.01350402],
       ...,
       [ 0.03081083, -0.04464164, -0.02021751, ..., -0.03949338,
        -0.01090325, -0.0010777 ],
       [-0.01277963, -0.04464164, -0.02345095, ..., -0.00259226,
        -0.03845972, -0.03835666],
       [-0.09269548, -0.04464164,  0.02828403, ..., -0.03949338,
        -0.00514219, -0.0010777 ]])

In [195]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [196]:
X_train

array([[ 1.49836523,  1.06136988,  0.21990201, ...,  0.71103773,
         0.54748197, -0.06144896],
       [-0.22885822,  1.06136988, -0.41936607, ...,  1.4842858 ,
        -0.01975653,  0.36723647],
       [ 0.08518241, -0.94217861,  1.01898711, ..., -0.06221033,
         0.3312366 , -0.31866022],
       ...,
       [ 0.63475351, -0.94217861, -0.46502808, ..., -0.83545839,
        -0.25375196, -0.06144896],
       [-0.30736838, -0.94217861, -0.53352109, ..., -0.06221033,
        -0.83072436, -0.83308273],
       [-2.03459183, -0.94217861,  0.56236706, ..., -0.83545839,
        -0.13312789, -0.06144896]])

In [197]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [198]:
print('mse is : ',mean_squared_error(y_test,y_pred))
print('r2_score is : ',r2_score(y_test,y_pred))

mse is :  2900.1936284934823
r2_score is :  0.45260276297191926

# RIDGE  REGRESSION

In [199]:
from sklearn.linear_model import RidgeCV

alphas = np.arange(0,1,0.01)

ridge_cv = RidgeCV(alphas=alphas, cv=5)
ridge_cv.fit(X_train, y_train)

print("Best alpha:", ridge_cv.alpha_)

Best alpha: 0.99

In [200]:
from sklearn.linear_model import Ridge

ridge=Ridge(alpha=0.99,solver='auto',max_iter=10000)
ridge.fit(X_train,y_train)
y_pred=ridge.predict(X_test)

In [201]:
print('mse is : ',mean_squared_error(y_test,y_pred))
print('r2_score is : ',r2_score(y_test,y_pred))

mse is :  2892.0707995895687
r2_score is :  0.45413590684726945

# LASSO REGRESSION

In [202]:
from sklearn.linear_model import LassoCV

lasso_cv = LassoCV(cv=5, random_state=42)
lasso_cv.fit(X_train, y_train)
alpha_value=lasso_cv.alpha_

print("Best alpha:", lasso_cv.alpha_)

Best alpha: 1.6552151706972245

In [203]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=alpha_value,max_iter=10000)
lasso.fit(X_train,y_train)
y_pred=lasso.predict(X_test)

In [204]:
print('mse is : ',mean_squared_error(y_test,y_pred))
print('r2_score is : ',r2_score(y_test,y_pred))

mse is :  2800.487334373644
r2_score is :  0.4714218340088624

# ELASTICNET REGRESSION

In [209]:
from sklearn.linear_model import ElasticNetCV

model = ElasticNetCV(cv=5, random_state=42)
model.fit(X_train, y_train)
best_alpha = model.alpha_
bestl1_ratio=model.l1_ratio_
print("Best alpha:", model.alpha_)
print("Best l1_ratio:", model.l1_ratio_)

Best alpha: 0.18943499524127286
Best l1_ratio: 0.5

In [216]:
from sklearn.linear_model import ElasticNet
elastic_net=ElasticNet(alpha=best_alpha,l1_ratio=bestl1_ratio)
elastic_net.fit(X_train,y_train)
y_pred=elastic_net.predict(X_test)

In [217]:
print('mse is : ',mean_squared_error(y_test,y_pred))
print('r2_score is : ',r2_score(y_test,y_pred))

mse is :  2855.9931467831357
r2_score is :  0.4609453857974588